CREATE TABLE `infovis`.`e2008mccain` (
  `cmte_id` VARCHAR(9) NULL,
  `cand_id` VARCHAR(9) NULL,
  `cand_nm` VARCHAR(45) NULL,
  `recipient_nm` VARCHAR(45) NULL,
  `disb_amt` INT NULL,
  `disb_dt` VARCHAR(45) NULL,
  `recipient_city` VARCHAR(25) NULL,
  `recipient_st` VARCHAR(2) NULL,
  `recipient_zip` VARCHAR(15) NULL,
  `disb_desc` VARCHAR(45) NULL,
  `memo_cd` VARCHAR(20) NULL,
  `memo_text` VARCHAR(45) NULL,
  `form_tp` VARCHAR(45) NULL,
  `file_num` VARCHAR(7) NULL,
  `tran_id` VARCHAR(45) NULL,
  `election_tp` VARCHAR(45) NULL);

CREATE TABLE `infovis`.`e2008obama` (
  `cmte_id` VARCHAR(9) NULL,
  `cand_id` VARCHAR(9) NULL,
  `cand_nm` VARCHAR(45) NULL,
  `recipient_nm` VARCHAR(45) NULL,
  `disb_amt` INT NULL,
  `disb_dt` VARCHAR(45) NULL,
  `recipient_city` VARCHAR(25) NULL,
  `recipient_st` VARCHAR(2) NULL,
  `recipient_zip` VARCHAR(15) NULL,
  `disb_desc` VARCHAR(45) NULL,
  `memo_cd` VARCHAR(20) NULL,
  `memo_text` VARCHAR(45) NULL,
  `form_tp` VARCHAR(45) NULL,
  `file_num` VARCHAR(7) NULL,
  `tran_id` VARCHAR(45) NULL,
  `election_tp` VARCHAR(45) NULL);

CREATE TABLE `infovis`.`e2012mitt` (
  `cmte_id` VARCHAR(9) NULL,
  `cand_id` VARCHAR(9) NULL,
  `cand_nm` VARCHAR(45) NULL,
  `recipient_nm` VARCHAR(45) NULL,
  `disb_amt` INT NULL,
  `disb_dt` VARCHAR(45) NULL,
  `recipient_city` VARCHAR(25) NULL,
  `recipient_st` VARCHAR(2) NULL,
  `recipient_zip` VARCHAR(15) NULL,
  `disb_desc` VARCHAR(45) NULL,
  `memo_cd` VARCHAR(20) NULL,
  `memo_text` VARCHAR(45) NULL,
  `form_tp` VARCHAR(45) NULL,
  `file_num` VARCHAR(7) NULL,
  `tran_id` VARCHAR(45) NULL,
  `election_tp` VARCHAR(45) NULL);

CREATE TABLE `infovis`.`e2012obama` (
  `cmte_id` VARCHAR(9) NULL,
  `cand_id` VARCHAR(9) NULL,
  `cand_nm` VARCHAR(45) NULL,
  `recipient_nm` VARCHAR(45) NULL,
  `disb_amt` INT NULL,
  `disb_dt` VARCHAR(45) NULL,
  `recipient_city` VARCHAR(25) NULL,
  `recipient_st` VARCHAR(2) NULL,
  `recipient_zip` VARCHAR(15) NULL,
  `disb_desc` VARCHAR(45) NULL,
  `memo_cd` VARCHAR(20) NULL,
  `memo_text` VARCHAR(45) NULL,
  `form_tp` VARCHAR(45) NULL,
  `file_num` VARCHAR(7) NULL,
  `tran_id` VARCHAR(45) NULL,
  `election_tp` VARCHAR(45) NULL);

CREATE TABLE `infovis`.`e2016clinton` (
  `cmte_id` VARCHAR(9) NULL,
  `cand_id` VARCHAR(9) NULL,
  `cand_nm` VARCHAR(45) NULL,
  `recipient_nm` VARCHAR(45) NULL,
  `disb_amt` INT NULL,
  `disb_dt` VARCHAR(45) NULL,
  `recipient_city` VARCHAR(25) NULL,
  `recipient_st` VARCHAR(2) NULL,
  `recipient_zip` VARCHAR(15) NULL,
  `disb_desc` VARCHAR(45) NULL,
  `memo_cd` VARCHAR(20) NULL,
  `memo_text` VARCHAR(45) NULL,
  `form_tp` VARCHAR(45) NULL,
  `file_num` VARCHAR(7) NULL,
  `tran_id` VARCHAR(45) NULL,
  `election_tp` VARCHAR(45) NULL);

CREATE TABLE `infovis`.`e2016trump` (
  `cmte_id` VARCHAR(9) NULL,
  `cand_id` VARCHAR(9) NULL,
  `cand_nm` VARCHAR(45) NULL,
  `recipient_nm` VARCHAR(45) NULL,
  `disb_amt` INT NULL,
  `disb_dt` VARCHAR(45) NULL,
  `recipient_city` VARCHAR(25) NULL,
  `recipient_st` VARCHAR(2) NULL,
  `recipient_zip` VARCHAR(15) NULL,
  `disb_desc` VARCHAR(45) NULL,
  `memo_cd` VARCHAR(20) NULL,
  `memo_text` VARCHAR(45) NULL,
  `form_tp` VARCHAR(45) NULL,
  `file_num` VARCHAR(7) NULL,
  `tran_id` VARCHAR(45) NULL,
  `election_tp` VARCHAR(45) NULL);