CREATE TABLE `infovis`.`c2008mccain` (
  `cmte_id` VARCHAR(9) NULL,
  `cand_id` VARCHAR(9) NULL,
  `cand_nm` VARCHAR(45) NULL,
  `contbr_nm` VARCHAR(45) NULL,
  `contbr_city` VARCHAR(25) NULL,
  `contbr_state` VARCHAR(2) NULL,
  `contbr_zip` VARCHAR(15) NULL,
  `contbr_employer` VARCHAR(45) NULL,
  `contbr_occupation` VARCHAR(45) NULL,
  `contb_receipt_amt` INT NULL,
  `contb_receipt_dt` VARCHAR(45) NULL,
  `receipt_desc` VARCHAR(45) NULL,
  `memo_cd` VARCHAR(20) NULL,
  `memo_text` VARCHAR(45) NULL,
  `form_tp` VARCHAR(45) NULL,
  `file_num` VARCHAR(7) NULL,
  `tran_id` VARCHAR(45) NULL,
  `election_tp` VARCHAR(45) NULL);

CREATE TABLE `infovis`.`c2008obama` (
  `cmte_id` VARCHAR(9) NULL,
  `cand_id` VARCHAR(9) NULL,
  `cand_nm` VARCHAR(45) NULL,
  `contbr_nm` VARCHAR(45) NULL,
  `contbr_city` VARCHAR(25) NULL,
  `contbr_state` VARCHAR(2) NULL,
  `contbr_zip` VARCHAR(15) NULL,
  `contbr_employer` VARCHAR(45) NULL,
  `contbr_occupation` VARCHAR(45) NULL,
  `contb_receipt_amt` INT NULL,
  `contb_receipt_dt` VARCHAR(45) NULL,
  `receipt_desc` VARCHAR(45) NULL,
  `memo_cd` VARCHAR(20) NULL,
  `memo_text` VARCHAR(45) NULL,
  `form_tp` VARCHAR(45) NULL,
  `file_num` VARCHAR(7) NULL,
  `tran_id` VARCHAR(45) NULL,
  `election_tp` VARCHAR(45) NULL);

CREATE TABLE `infovis`.`c2012mitt` (
  `cmte_id` VARCHAR(9) NULL,
  `cand_id` VARCHAR(9) NULL,
  `cand_nm` VARCHAR(45) NULL,
  `contbr_nm` VARCHAR(45) NULL,
  `contbr_city` VARCHAR(25) NULL,
  `contbr_state` VARCHAR(2) NULL,
  `contbr_zip` VARCHAR(15) NULL,
  `contbr_employer` VARCHAR(45) NULL,
  `contbr_occupation` VARCHAR(45) NULL,
  `contb_receipt_amt` INT NULL,
  `contb_receipt_dt` VARCHAR(45) NULL,
  `receipt_desc` VARCHAR(45) NULL,
  `memo_cd` VARCHAR(20) NULL,
  `memo_text` VARCHAR(45) NULL,
  `form_tp` VARCHAR(45) NULL,
  `file_num` VARCHAR(7) NULL,
  `tran_id` VARCHAR(45) NULL,
  `election_tp` VARCHAR(45) NULL);

CREATE TABLE `infovis`.`c2012obama` (
  `cmte_id` VARCHAR(9) NULL,
  `cand_id` VARCHAR(9) NULL,
  `cand_nm` VARCHAR(45) NULL,
  `contbr_nm` VARCHAR(45) NULL,
  `contbr_city` VARCHAR(25) NULL,
  `contbr_state` VARCHAR(2) NULL,
  `contbr_zip` VARCHAR(15) NULL,
  `contbr_employer` VARCHAR(45) NULL,
  `contbr_occupation` VARCHAR(45) NULL,
  `contb_receipt_amt` INT NULL,
  `contb_receipt_dt` VARCHAR(45) NULL,
  `receipt_desc` VARCHAR(45) NULL,
  `memo_cd` VARCHAR(20) NULL,
  `memo_text` VARCHAR(45) NULL,
  `form_tp` VARCHAR(45) NULL,
  `file_num` VARCHAR(7) NULL,
  `tran_id` VARCHAR(45) NULL,
  `election_tp` VARCHAR(45) NULL);

CREATE TABLE `infovis`.`c2016clinton` (
  `cmte_id` VARCHAR(9) NULL,
  `cand_id` VARCHAR(9) NULL,
  `cand_nm` VARCHAR(45) NULL,
  `contbr_nm` VARCHAR(45) NULL,
  `contbr_city` VARCHAR(25) NULL,
  `contbr_state` VARCHAR(2) NULL,
  `contbr_zip` VARCHAR(15) NULL,
  `contbr_employer` VARCHAR(45) NULL,
  `contbr_occupation` VARCHAR(45) NULL,
  `contb_receipt_amt` INT NULL,
  `contb_receipt_dt` VARCHAR(45) NULL,
  `receipt_desc` VARCHAR(45) NULL,
  `memo_cd` VARCHAR(20) NULL,
  `memo_text` VARCHAR(45) NULL,
  `form_tp` VARCHAR(45) NULL,
  `file_num` VARCHAR(7) NULL,
  `tran_id` VARCHAR(45) NULL,
  `election_tp` VARCHAR(45) NULL);


CREATE TABLE `infovis`.`c2016trump` (
  `cmte_id` VARCHAR(9) NULL,
  `cand_id` VARCHAR(9) NULL,
  `cand_nm` VARCHAR(45) NULL,
  `contbr_nm` VARCHAR(45) NULL,
  `contbr_city` VARCHAR(25) NULL,
  `contbr_state` VARCHAR(2) NULL,
  `contbr_zip` VARCHAR(15) NULL,
  `contbr_employer` VARCHAR(45) NULL,
  `contbr_occupation` VARCHAR(45) NULL,
  `contb_receipt_amt` INT NULL,
  `contb_receipt_dt` VARCHAR(45) NULL,
  `receipt_desc` VARCHAR(45) NULL,
  `memo_cd` VARCHAR(20) NULL,
  `memo_text` VARCHAR(45) NULL,
  `form_tp` VARCHAR(45) NULL,
  `file_num` VARCHAR(7) NULL,
  `tran_id` VARCHAR(45) NULL,
  `election_tp` VARCHAR(45) NULL);