SELECT distinct(contbr_state) FROM infovis.c2016clinton WHERE 
contbr_state <> 'AL' AND 
contbr_state <> 'AK' AND
contbr_state <> 'AZ' AND
contbr_state <> 'AR' AND
contbr_state <> 'CA' AND
contbr_state <> 'CO' AND
contbr_state <> 'CT' AND
contbr_state <> 'DE' AND
contbr_state <> 'FL' AND
contbr_state <> 'GA' AND
contbr_state <> 'HI' AND
contbr_state <> 'ID' AND
contbr_state <> 'IL' AND
contbr_state <> 'IN' AND
contbr_state <> 'IA' AND
contbr_state <> 'KS' AND
contbr_state <> 'KY' AND
contbr_state <> 'LA' AND
contbr_state <> 'ME' AND
contbr_state <> 'MD' AND
contbr_state <> 'MA' AND
contbr_state <> 'MI' AND
contbr_state <> 'MN' AND
contbr_state <> 'MS' AND
contbr_state <> 'MO' AND
contbr_state <> 'MT' AND
contbr_state <> 'NE' AND
contbr_state <> 'NV' AND
contbr_state <> 'NH' AND
contbr_state <> 'NJ' AND
contbr_state <> 'NM' AND
contbr_state <> 'NY' AND
contbr_state <> 'NC' AND
contbr_state <> 'ND' AND
contbr_state <> 'OH' AND
contbr_state <> 'OK' AND
contbr_state <> 'OR' AND
contbr_state <> 'PA' AND
contbr_state <> 'RI' AND
contbr_state <> 'SC' AND
contbr_state <> 'SD' AND
contbr_state <> 'TN' AND
contbr_state <> 'TX' AND
contbr_state <> 'UT' AND
contbr_state <> 'VT' AND
contbr_state <> 'VA' AND
contbr_state <> 'WA' AND
contbr_state <> 'WV' AND
contbr_state <> 'WI' AND
contbr_state <> 'WY' AND
contbr_state <> 'AS' AND
contbr_state <> 'DC' AND
contbr_state <> 'FM' AND
contbr_state <> 'GU' AND
contbr_state <> 'MH' AND
contbr_state <> 'MP' AND
contbr_state <> 'PW' AND
contbr_state <> 'PR' AND
contbr_state <> 'VI';