LOAD DATA LOCAL INFILE '/Users/hotshot/Documents/3rdSem/CS7450_InfoVis/Project/ContributorData/2008McCain/P80002801-ALL.csv' INTO TABLE c2008mccain
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/Users/hotshot/Documents/3rdSem/CS7450_InfoVis/Project/ContributorData/2008Obama/P80003338-ALL.csv' INTO TABLE c2008obama
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/Users/hotshot/Documents/3rdSem/CS7450_InfoVis/Project/ContributorData/2012Mitt/P80003353-ALL.csv' INTO TABLE c2012mitt
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;
  
LOAD DATA LOCAL INFILE '/Users/hotshot/Documents/3rdSem/CS7450_InfoVis/Project/ContributorData/2012Obama/P80003338-ALL.csv' INTO TABLE c2012obama
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/Users/hotshot/Documents/3rdSem/CS7450_InfoVis/Project/ContributorData/2016Clinton/P00003392-ALL.csv' INTO TABLE c2016clinton
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/Users/hotshot/Documents/3rdSem/CS7450_InfoVis/Project/ContributorData/2016Trump/P80001571-ALL.csv' INTO TABLE c2016trump
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;