LOAD DATA LOCAL INFILE '/Users/hotshot/Documents/3rdSem/CS7450_InfoVis/Project/ExpenditureData/2008McCain/P80002801D-ALL.csv' INTO TABLE e2008mccain
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/Users/hotshot/Documents/3rdSem/CS7450_InfoVis/Project/ExpenditureData/2008Obama/P80003338D-ALL.csv' INTO TABLE e2008obama
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/Users/hotshot/Documents/3rdSem/CS7450_InfoVis/Project/ExpenditureData/2012Mitt/P80003353D-ALL.csv' INTO TABLE e2012mitt
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/Users/hotshot/Documents/3rdSem/CS7450_InfoVis/Project/ExpenditureData/2012Obama/P80003338D-ALL.csv' INTO TABLE e2012obama
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/Users/hotshot/Documents/3rdSem/CS7450_InfoVis/Project/ExpenditureData/2016Clinton/P00003392D-ALL.csv' INTO TABLE e2016clinton
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/Users/hotshot/Documents/3rdSem/CS7450_InfoVis/Project/ExpenditureData/2016Trump/P80001571D-ALL.csv' INTO TABLE e2016trump
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;